<?php

declare(strict_types=1);

namespace SharpAPI\ContentDetectAi;

use GuzzleHttp\Exception\GuzzleException;
use InvalidArgumentException;
use SharpAPI\Core\Client\SharpApiClient;

/**
 * @api
 */
class ContentDetectAiService extends SharpApiClient
{
    /**
     * Initializes a new instance of the class.
     *
     * @throws InvalidArgumentException if the API key is empty.
     */
    public function __construct()
    {
        parent::__construct(config('sharpapi-content-detect-ai.api_key'));
        $this->setApiBaseUrl(
            config(
                'sharpapi-content-detect-ai.base_url',
                'https://sharpapi.com/api/v1'
            )
        );
        $this->setApiJobStatusPollingInterval(
            (int) config(
                'sharpapi-content-detect-ai.api_job_status_polling_interval',
                5)
        );
        $this->setApiJobStatusPollingWait(
            (int) config(
                'sharpapi-content-detect-ai.api_job_status_polling_wait',
                180)
        );
        $this->setUserAgent('SharpAPILaravelContentDetectAi/1.0.0');
    }

    /**
     * Analyzes the provided text to detect if it was generated by AI.
     * Returns a likelihood score, assessment, reasoning, and flagged parts
     * that indicate AI-generated patterns such as specific vocabulary,
     * excessive transitional phrases, and other stylistic markers.
     *
     * @throws GuzzleException
     *
     * @api
     */
    public function detectAi(string $text): string
    {
        $response = $this->makeRequest(
            'POST',
            '/content/detect_ai',
            ['content' => $text]
        );

        return $this->parseStatusUrl($response);
    }
}
